sudo: required
services: 
  - docker

before_install: 
  - docker build -t shreshthyash/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run shreshthyash/react-test npm test -- --coverage

after_success: 
  - docker build -t shreshthyash/multi-client ./client 
  - docker build -t shreshthyash/multi-nginx ./nginx 
  - docker build -t shreshthyash/multi-server ./server 
  - docker build -t shreshthyash/multi-worker ./worker 
#login to docker hub CLI.. 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
#take them to push to docker hub.. 
  - docker push shreshthyash/multi-client 
  - docker push shreshthyash/multi-nginx 
  - docker push shreshthyash/multi-server 
  - docker push shreshthyash/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-398061251695"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  seceret_access_key: "$AWS_SECRET_KEY"