sudo: required
services: 
  - docker

before_install: 
  - docker build -t shreshthyash/react-test -f ./client/Dockerfile.dev .

script: 
  - docker run shreshthyash/react-test npm test -- --coverage

after_sucess: 
  - docker build -t shreshthyash/multi-client ./client 
  - docker build -t shreshthyash/multi-nginx ./nginx 
  - docker build -t shreshthyash/multi-server ./server 
  - docker build -t shreshthyash/multi-worker ./worker 
#login to docker hub CLI. 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
#take them to push to docker hub. 
  -docker push shreshthyash/multi-client 
  -docker push shreshthyash/multi-nginx 
  -docker push shreshthyash/multi-server 
  -docker push shreshthyash/multi-worker